title: Positronics Lab
author: "@ The George Washington University"
description: "Planning Optimization and Simulation for Robotics"
url: http://positronicslab.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
gems: [jekyll-paginate]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 20

navigation:
 - title: Home
   url: /
 - title: People
   url: /people
 - title: Research
   url: /research
 - title: Publications
   url: /publications
 - title: Code
   url: /code

social:
   github: positronicslab
#   twitter: 
#   facebook: 
#   email: 

google_analytics: "UA-73497600-1"
